test_script:
- ps: .\test.ps1
init:
  - ps: |
      $newPath = ($env:PATH.split(';') | ? {$_ -notmatch "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\1[37]0\\"} ) -join ';'
      [Environment]::SetEnvironmentVariable("Path", $newPath + ";C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\180\Tools\Binn\", "machine")
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build: off

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
